[clades] make output arg required
If the argument isn't provided we would get a traceback (see below), so
make it required

```
Traceback (most recent call last):
  File "/Users/naboo/github/nextstrain/augur/augur/__init__.py", line 70, in run
    return args.__command__.run(args)
  File "/Users/naboo/github/nextstrain/augur/augur/clades.py", line 385, in run
    out_name = get_json_name(args)
  File "/Users/naboo/github/nextstrain/augur/augur/utils.py", line 43, in get_json_name
    raise ValueError("Please specify a name for the JSON file containing the results.")
ValueError: Please specify a name for the JSON file containing the results.
````