python2 deps: Increment versions of Matplotlib and Seaborn
With the previous requirements of matplotlib version 2.0 and seaborn 0.6 I was getting a conflict when loading both packages stating:
```
KeyError: 'axes.color_cycle is not a valid rc parameter. See rcParams.keys() for a list of valid parameters.'
```
Incrementing versions fixes the issue and doesn't appear to cause issues.