translate: Fix error handling of reference sequence features
Previously, the error message was never reached because len(features)
would raise another error:

    TypeError: object of type 'NoneType' has no len()

Switching the order allows for the intended error handling to happen.